### ISSUE TITLE
Some problems with the new version

### ISSUE THREAD

**Issue by claell** [Laverna/laverna#300]
Thanks for rewriting so much. Unfortunately I am facing some problems using it. In Firefox loading does never finish (https://laverna.cc/app/) and on Chrome it loads, but I don't know, whether Importing settings works. I don't get a message that they ware imported (probably they were).

Also the Dropbox authorisation page shows an Error message. Please say if you need more details.

**Comment by wwwredfish** [comment]
What version of Firefox are you using?
Right now the app doesn't notify you when the importing is done (it is something that we are going to address soon).
We will fix Dropbox in a second.

**Comment by wwwredfish** [comment]
You should be able to connect to Dropbox now.

**Comment by claell** [comment]
Thanks for the fast response.

I am using Firefox 42.0. Mabye this is a problem caused by the older version stored locally?

Dropbox authentication works, thank you :)

Unfortunately my notes stored in Dropbox from the old version do not seem to get synced to the new Laverna version.

**Comment by wwwredfish** [comment]
We will check it out, though I doubt it's because of the older version.
We changed the structure of files in Dropbox, so you need to first synchronize with it in a browser where you have the data.

**Comment by claell** [comment]
Alright. I am using Ubuntu 15.10 by the way.

So is there a link to the old version, so I can sync them with Chrome (since Firefox does not work and it is the only browser where I have the notes locally)?

**Comment by wwwredfish** [comment]
In Firefox, can you press F12, switch to 'console' tab, update the page, and take a screenshot after several seconds?
To transfer your notes, you can also move your old notes to a 'notes-db/notes' folder on Dropbox. (for notebooks - 'notes-db/notebooks', for tags - 'notes-db/tags')

**Comment by claell** [comment]
![bildschirmfoto vom 2015-12-04 22-51-02](https://cloud.githubusercontent.com/assets/6171135/11602304/85fd7074-9ad9-11e5-88f0-9079f32bb136.png)
Is this the right section in the console tab?

Will try the transferring.

**Comment by wwebfor** [comment]
Konsole is the right tab.

**Comment by claell** [comment]
I did not read the text careful enough, thanks for clarifying.

![bildschirmfoto vom 2015-12-04 22-55-07](https://cloud.githubusercontent.com/assets/6171135/11602381/25a36462-9ada-11e5-937c-4009c8b4f829.png)

**Comment by wwwredfish** [comment]
It seems like indexedDB is not available for some reason, are you in a Private browsing mode? Or perhaps some kind of extension is blocking it.

BTW. We have uploaded old version of the Laverna. You can access it here: https://laverna.cc/old.html

**Comment by claell** [comment]
I don't use private browsing, but could try deactivating some extensions.

**Comment by claell** [comment]
Still the same problems with all extensions deactivated.

**Comment by wwwredfish** [comment]
Try to set "Firefox will: Remember history" in the preferences panel of Firefox.

**Comment by wwebfor** [comment]
about:preferences#privacy

**Comment by claell** [comment]
![bildschirmfoto vom 2015-12-04 23-35-53](https://cloud.githubusercontent.com/assets/6171135/11603134/db8fd03a-9adf-11e5-8091-3624f06ad4cd.png)

Still not working, unfortunately.

**Comment by claell** [comment]
It is definitely something caused by my settings. Just tried it with a clean Firefox by renaming the settings folder and it worked.

**Comment by wwebfor** [comment]
If that's the case, probably either indexeddb was disabled specifically or the database was damaged.

To test if IndexedDb was disabled, open ``about:config``. Then, search for ``dom.indexedDB.enabled``. It should be set to true.

**Comment by wwebfor** [comment]
Also to test if settings are to blame, you can ran Firefox in a safe mode.

```
firefox --safe-mode
```

Or if all your notes are synchronized with Dropbox, you can just create a new folder named ``notes-db`` in Dropbox ``https://www.dropbox.com/home/Apps/Laverna``. Then, copy all folders in their inside notes-db. It should sync everything.

**Comment by claell** [comment]
The IndesedDb is enabled in about:config for me.

Interesting thing is that the problem occurs in safe mode of Firefox as well.

**Comment by git-in-my-anus** [comment]
New app doesn't work for me too. I am using the latest Firefox.

Also after trying to open a new app, old one broke completely (the one from 'index.html' (stored in cache I assume) was working fine just minutes before). There is only empty left side pane on the screen. The error in my console for the old app is:
```
AppNote is started 96b2d9d9.main.js:28:9023
opening database notes-db in version #6 96b2d9d9.main.js:9:4338
VersionError #this one is error, others are just logs
```

New app gives me the following error:
```
opening database notes-db in version #8 main.js:184:11456
execute : read on configs for useDefaultConfigs main.js:184:11456
NotFoundError: The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened. main.js:184:0
```
IndexedDB is allowed in settings.

I also have noted the database files with my notes in dropbox are quite old, maybe because there were some errors in sync config, after I have turned off encryption. With this situation and new errors in mind, can you tell me please, how can I safely export my current db in plaintext format?
Thanks.

**Comment by wwebfor** [comment]
Alright, can you try to open https://laverna.cc/dist? Maybe there it will work.

**Comment by git-in-my-anus** [comment]
Yeah, it works, thanks.

**Comment by wwebfor** [comment]
You're welcome. I'm glad it helped.

**Comment by romu70** [comment]
Hi,
I've got some issues too. Indexed-db is enabled within Firefox. And your trick about creating the notes-db folder works.

Indeed there are several issues:
- the application name within DropBox has changed from RTLaverna to Laverna.
- If I try to enter my API key (which is optional though), I get an ERROR 400 page.

I use Laverna on 3 devices: 2 PCs and a phone. And now I've connected the 3 devices, I think my DropBox storage is a mess, here is what I have:
- Laverna
 - notes-db
  - notebooks
  - notes
- RTLaverna
 - notebooks
 - notes
 - notes-db
  - notes

Need some advices here about what I've to do to fix this.

Thanks.

**Comment by wwwredfish** [comment]
If you are using your custom dropbox key, you need to add a new redirect URL in Dropbox App settings. For laverna.cc domain: https://laverna.cc/app/dropbox.html

**Comment by romu70** [comment]
Ok thanks, this trick works. I've been able to clean up the notes folders within DropBox. Seems great to me, I've just a remaining issue, I've created an issue about this.

**Comment by claell** [comment]
I just tried to load the new version of Laverna on a different machine, Firefox sync enabled and get the same issue.

**Comment by wwwredfish** [comment]
By the same issue do you mean Error 400 on Dropbox?

**Comment by claell** [comment]
No, the infinite loading problem.

**Comment by wwwredfish** [comment]
Have you tried to open https://laverna.cc/dist?

**Comment by claell** [comment]
Yes, got this:
![bildschirmfoto vom 2015-12-07 20-07-11](https://cloud.githubusercontent.com/assets/6171135/11636789/2ffefe58-9d1e-11e5-9bad-7b3eebb40480.png)

**Comment by wwwredfish** [comment]
I see. We will be working primarily on this issue then. Thank you for your patience.

**Comment by claell** [comment]
No problem. Thanks for trying to fix this, as it is probably a very unique issue. I hope this can get fixed and will try to help as much as I can.

**Comment by ggarek** [comment]
Hi there, i have some issues with new version laverna.cc as well. Here are the details, i prepared after reading through the thread. 

chrome:version//
<img width="941" alt="screen shot 2015-12-10 at 10 21 48" src="https://cloud.githubusercontent.com/assets/5501062/11709356/ebd85470-9f27-11e5-98df-7558fe1c19cb.png">

https://laverna.cc/old.html loads just fine, and i can browse all my notes.

https://laverna.cc/app/ does not work (here is console tab screen)
<img width="781" alt="screen shot 2015-12-10 at 10 24 11" src="https://cloud.githubusercontent.com/assets/5501062/11709385/3619bc90-9f28-11e5-9b9b-c0e63c7d68fe.png">

https://laverna.cc/dist/ does not work either
<img width="830" alt="screen shot 2015-12-10 at 10 27 44" src="https://cloud.githubusercontent.com/assets/5501062/11709428/bcaef2fc-9f28-11e5-8fe7-91f23a3c68aa.png">

**Comment by claell** [comment]
Have you used laverna before the update? Maybe it is something from the old version that prevents the new one from loading.

**Comment by ggarek** [comment]
Sure, i used it. I did not set up dropbox or other stuff. I just used it as is. Yesterday i opened old.html and it worked fine. But today even it stopped working. 

Here is the screen of https://laverna.cc/old.html

<img width="1264" alt="screen shot 2015-12-11 at 10 14 32" src="https://cloud.githubusercontent.com/assets/5501062/11738050/325af24a-9ff0-11e5-83de-8d9684fd0e49.png">

**Comment by wwebfor** [comment]
@ggarek today we will publish RC release. Probably it will resolve the issue. All of those bugs appeared because of reliance on database versions.

**Comment by ggarek** [comment]
@wwebfor Thank you, i will check it after it is released.

**Comment by wwebfor** [comment]
We have just published a pre-release. It should fix most problems described in this issue. A pre-release can be accessed at https://laverna.cc/nightly

**Comment by ggarek** [comment]
Just tried it, still no luck. Waited until all Cache events are resolved, it took a while.

 Here are some screens

<img width="957" alt="screen shot 2015-12-11 at 18 53 05" src="https://cloud.githubusercontent.com/assets/5501062/11748319/b9eb6e2c-a038-11e5-939a-adb0d74bd13b.png">
<img width="963" alt="screen shot 2015-12-11 at 18 53 22" src="https://cloud.githubusercontent.com/assets/5501062/11748321/baddcd8e-a038-11e5-8f32-2b605263a970.png">

**Comment by wwebfor** [comment]
Very strange. According to the console output, there aren't any errors. It should work. We tried to recreate this bug with our data with no avail.

Do you use encryption? If you don't or you backed up your encryption settings, your notes probably still can be recovered. In the next week we will implement importing functionality.

**Comment by ggarek** [comment]
I don`t know, used it as is. No settings amended. What can i do to restore/export my notes if it is even possible?

**Comment by wwebfor** [comment]
Yes, it should be possible. As I said, we will implement import/export functionality in the next week. We will start working on it as soon as possible.

--------

For now, you can just backup database files in order to have a backup file in case if you accidentally clear cache in Chrome. Because if you clear it, your notes will be gone.

All data is stored in your browser's profile. In case with Chrome, Indexeddb data is stored in a LevelDB file.

For Chromium, those files are usually located in:
* Linux: `~/.config/chromium/Default/IndexedDB/`
* Windows: `%AppData%\Local\Google\Chrome\User Data\Default`

**Comment by ggarek** [comment]
One more thing, i just tried to connect to 'notes-db' - the operation never finished. But for "MyTestDatabse" it succeed.

<img width="1107" alt="screen shot 2015-12-11 at 20 26 56" src="https://cloud.githubusercontent.com/assets/5501062/11750736/f7ef2f76-a045-11e5-9637-906a9ebc4a21.png">

There is one more observation. There is 3 indexeddb in Resources tab one of wich is notes-db. Whenever i click to notes-db - the details window keep displaying previous state whatever it was.

<img width="685" alt="screen shot 2015-12-11 at 20 34 00" src="https://cloud.githubusercontent.com/assets/5501062/11750811/8d222eae-a046-11e5-8c1a-76e31b9d221f.png">

**Comment by wwebfor** [comment]
Probably you don't have a permission to open that database. Also, on the screenshot it indicates that `notes-db` is empty.

Can you try to give yourself permissions to read and write files in Chrome/Default/IndexedDB/*laverna.cc* with `chown` or `chmod`?

**Comment by ggarek** [comment]
> Also, on the screenshot it indicates that notes-db is empty.

Whenever i click on notes-db - the details window keep displaying previous state whatever it was. Which means it does not respond or kind of.

> Can you try to give yourself permissions to read and write files in Chrome/Default/IndexedDB/laverna.cc with chown or chmod?

I did it and it did not help. But then i understood what was the problem. And i am ashamed for spending your time :sob: ! Thank you for for trying to help!

*The app was not loading, because, there was another one tab opened with the app. I did not see it, because there is a lot tabs.* 

May be you can detect that there is another tab opened, and notify user.

Thanks for help!

**Comment by wwebfor** [comment]
It's OK. I was worried we caused some data loss. It is good to hear everything is alright :).

We suggest to enable synchronization with some cloud storage to avoid data loss or to set up auto backup of IndexedDB files. Thank you for you patience.

**Comment by ggarek** [comment]
:+1: 

I will certainly setup sync.
Just checked if the app works with several tabs opened and it did. It seems the problem was that one of my tabs used previous version of laverna and blocked new instances somehow.

**Comment by claell** [comment]
Now I get this (still infinite loading):
![bildschirmfoto vom 2015-12-11 21-44-12](https://cloud.githubusercontent.com/assets/6171135/11755333/f637d94c-a051-11e5-8cc2-fecb1f8dfb03.png)

**Comment by claell** [comment]
On Chrome there are some UI elements missing:

![bildschirmfoto vom 2015-12-11 22-22-16](https://cloud.githubusercontent.com/assets/6171135/11755884/c799c286-a055-11e5-9909-100b41ad76a8.png)

**Comment by wwebfor** [comment]
@claell that is very strange. We will look at the issue later.

**Comment by claell** [comment]
Alright, thanks again. It seems like this issue is mainly happening, when there was a different version of Laverna opened some time before.
On Chromium for example I did not get missing UI elements (I had opened Laverna 0.7.0 there, but did not set up sync).

Also as I posted I got no elements at all when I opened https://laverna.cc/dist/ on Firefox while on Chrome I get this problem when opening https://laverna.cc/old.html
https://laverna.cc/dist/ works on Chrome.

So to me it looks as the multiple versions of Laverna might be blocking each other in some way.

**Comment by wwebfor** [comment]
@git-in-my-anus if you steel need to export your data into Markdown files, we have just released a nightly version where exporting and importing feature were added.

**Comment by wwebfor** [comment]
@claell probably your problems probably can be solved by migrating your data. In order to so, you need to open https://laverna.cc/nightly/migrate.html.

**Comment by claell** [comment]
@wwebfor just tried, but unfortunately still the same problem.

**Comment by claell** [comment]
![bildschirmfoto vom 2015-12-18 15-44-22](https://cloud.githubusercontent.com/assets/6171135/11899289/3c0d700c-a59e-11e5-8d03-7c8dff9c4e89.png)

**Comment by wwebfor** [comment]
Did you close the third tab before trying?

**Comment by claell** [comment]
No, but now I tried and still the same problem. Also in a different browser I cannot see the new features in the Nightly version unfortunately. Have you uploaded the new version already?

**Comment by wwebfor** [comment]
Yes we did. Also we updated appcache file.

**Comment by claell** [comment]
Weired. For example exporting notes is missing for me.

**Comment by wwebfor** [comment]
It should be on this page #/settings/importExport

**Comment by claell** [comment]
![bildschirmfoto vom 2015-12-18 15-53-03](https://cloud.githubusercontent.com/assets/6171135/11899467/72fcd548-a59f-11e5-83a9-3b25a1cf0a26.png)

**Comment by claell** [comment]
Also showing still 0.7.1-rc
![bildschirmfoto vom 2015-12-18 15-55-24](https://cloud.githubusercontent.com/assets/6171135/11899526/d20ed0c2-a59f-11e5-9345-8f8b7d26c8de.png)

**Comment by wwebfor** [comment]
Can you try to run key combination ```Ctrl+Shift+r`` in your browser. It should force your browser to load new versions of files.

**Comment by claell** [comment]
I already tried it.

**Comment by claell** [comment]
Deleting browser cache and cookies helped.

**Comment by wwebfor** [comment]
Can you try to run this command in you Firefox developer console on page laverna.cc:

```js
var req = indexedDB.open('notes-db'); req.onsuccess = function() {console.log('success');}; req.onerror = function(e) {console.error('Error', e);}
```

**Comment by claell** [comment]
On the nightly version?

**Comment by wwebfor** [comment]
It doesn't matter as long as you are on laverna.cc

**Comment by claell** [comment]
![bildschirmfoto vom 2015-12-18 16-06-09](https://cloud.githubusercontent.com/assets/6171135/11899716/49440364-a5a1-11e5-8abf-b39c60f1fdb2.png)

**Comment by wwebfor** [comment]
It is a bug in Firefox https://bugzil.la/1143003

If you have synchronized everything with a cloud storage, you can try to remove the database and reload the page. With this command you can remove the database:

```
indexedDB.deleteDatabase('notes-db');
```

**Comment by claell** [comment]
Worked, thanks. Interesting thing is that the settings seem to have been transferred. Cloud sync worked immediately after reloading the site.

**Comment by claell** [comment]
Same issue with nightly though, got Beta v0.7.1-rc still.

**Comment by wwebfor** [comment]
Do you mean on Firefox it shows v0.7.1-rc?

**Comment by claell** [comment]
Yes.

**Comment by wwebfor** [comment]
Seems like something is wrong with our appcache file. We'll fix it later. Regarding settings, probably it got your settings from localStorage (in previous version we used to store settings in localStorage)

**Comment by claell** [comment]
Alright. Thanks for helping with this issue. Seems it can be closed?

**Comment by wwebfor** [comment]
Thank you for your patience. Closing the issue since you agreed it was fixed.

**Comment by claell** [comment]
No problem, wasn't even your fault, apparently.

**Comment by git-in-my-anus** [comment]
@wwebfor Thanks. I have successfully exported data in the nightly version.
