### ISSUE TITLE
Laverna on Palemoon - MathJax library not found

### ISSUE THREAD

**Issue by illTimber** [Laverna/laverna#460]
Trying to access Laverna via [Palemoon](https://www.palemoon.org/) browser and, after clicking Start Using, the Loading... message just sits there. Only error info is the message "Your browser does not support MathJax". 

I posted in the Palemoon forums and the browser does path MathJax browser tests so maybe there is something other than that as the root cause.

Please support browser diversity and help the site work with Palemoon.

**Comment by wwebfor** [comment]
Which version do you use (you can find out by opening "About" page)?

**Comment by illTimber** [comment]
Palemoon version 26.2.2 (x64)
When I log in to Laverna on Firefox, the Laverna version is Laverna Beta v0.7.1

**Comment by wwebfor** [comment]
I've just checked and it seems to be working. We fixed this issue recently. It was linked to WebWorkers. For some reason they weren't working as expected. As a temporary solution, we just disabled webworkers in PaleMoon and Sailfish.

Source: https://github.com/Laverna/laverna/commit/2a5f604b7bb180c921c8fd24b39bcb0e7edd465e

**Comment by illTimber** [comment]
Nope. Still broken for me. I'm using Palemoon 26.2.2 (x64) on Windows 10 Pro Version 1511 with all updates installed. I've run Palemoon in safe mode with no plugins enabled and Laverna still doesn't load.
